### PR TITLE
Add maven support, block change packet support, explosion support and end portal support

### PR DESCRIPTION
**Pull request by TheGreatRambler**
Before I have this merged, I want to implement ender eyes being placed in end portal frames, I had to specifically blacklist them because an "ENDER_EYE" material was trying to be placed, which is impossible

### CODE REVIEW

**Comment by TheGreatRambler** [comment]
If I update the spigot api to 1.14.4 I could use functions from there (cast to `EndPortalFrame` and `setEye`) but I'm afraid that would break compatibility for old versions

**Comment by TheGreatRambler** [comment]
There's also a few other features I'd like to add, like doors and sounds, that I could use some help with

**Comment by TheGreatRambler** [comment]
Also how to add better spectating, the default spectating doesn't render chunks as you move or when teleporting to another world, you have to leave and then respectate.

**Comment by Jumper251** [comment]
The update to the 1.14.4 API would probably break some stuff.
If you want to change other features like the spectating function, a separate pull request might be better.
On which versions did you test your changes?

**Comment by Jumper251** [comment]
What is the point of the getReplayTickLength method?

**Comment by TheGreatRambler** [comment]
I didn't test this fork on any version other than 1.16, now that you say it. I have updated my fork significantly since this PR however, adding support for end portal frames with eyes, but it's a mega breaking change, a complete overhaul of the ItemData class. It does work on 1.12 and 1.16 however, which seemed to be a good pre flattening/post flattening test. As for getReplayTickLength, I added that as I intend to use it from another plugin, which is why I'm making these changes anyway.

**Comment by TheGreatRambler** [comment]
The main way I made the switch was using XMaterial and XBlock, which takes care of most version differences.

**Comment by Jumper251** [comment]
getReplayTickLength seems to be for a specific use case in your plugin, maybe it doesn't belong in the ReplayAPI.

I am not that experienced with maven but it looks like this will break compatibility with Java 8. Another thing I noticed why are you cancelling TNT explosions?

**Comment by Aldiwildan77** [comment]
TNT explosions can be handled by config `real_changes: false` in the blocks key, if this code is changing these explosions I suggest creating a new config for a TNT explosion.

**Comment by TheGreatRambler** [comment]
I disabled them and supported them instead during recording because explosions are not deterministic, they explode different blocks each time. I can change the Java version logic tho.

**Comment by TheGreatRambler** [comment]
Considering how much I've changed, I'll just close this pr and keep my fork separate for now

**Pull request closed without merging**
